model: 
  _target_: sklearn.ensemble.RandomForestClassifier
  n_estimators: 100
  max_features: "auto"
  max_depth: 10
  criterion: "entropy"

columns: ["feature1", "feature2", "feature3", "feature4"]  # Replace with actual feature names
cf: "features"
